### ISSUE TITLE
Signature logo converts to an attachment

### ISSUE THREAD

**Issue by applesolbrilla** [CanaryMail/Tickets#13]
App version: v413

Signature logos in both incoming and outgoing emails convert to an attachment.

![screenshot](https://user-images.githubusercontent.com/30912049/39404165-c96690b8-4bbf-11e8-88ae-a582b2147c71.jpeg)

Tag: signature logo

https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/1902146/conversations/15951914881

**Comment by dsanghan** [comment]
This is expected behavior. Not a bug.
