### ISSUE TITLE
Right clicking on an email only shows "Delete" after using the app for a period of time

### ISSUE THREAD

**Issue by applesolbrilla** [CanaryMail/Tickets#14]
App version: v413

When you open the app, right clicking on an email shows you this menu:

![1](https://user-images.githubusercontent.com/30912049/39404200-2bba87dc-4bc1-11e8-904e-86c237b74484.png)

After a couple of minutes of using the app, right clicking on an email shows you this:

![2](https://user-images.githubusercontent.com/30912049/39404217-74f81f9a-4bc1-11e8-9b5a-1caf0957671a.png)

Tag: right click menu

https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/1902146/conversations/15985765837

**Comment by dsanghan** [comment]
Fixed in 431
