### ISSUE TITLE
Templates not syncing

### ISSUE THREAD

**Issue by applesolbrilla** [CanaryMail/Tickets#15]
MacOS: App version 413
iOS: App version 2.05

Steps to reproduce the issue:

1. Turned on iCloud Sync on Mac and iOS.
2. Created a template on Mac.
3. Created a template on iOS.

The templates are not syncing across devices.

Tag: templates

Open ticket:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/1902146/conversations/16289152668

![img_2076](https://user-images.githubusercontent.com/30912049/40269850-33e5bc9c-5bb6-11e8-83a0-d3aa881fb612.PNG)
![img_2077](https://user-images.githubusercontent.com/30912049/40269851-3429764e-5bb6-11e8-8151-436c5ef775b8.PNG)
![img_2078](https://user-images.githubusercontent.com/30912049/40269852-3466303e-5bb6-11e8-8e8e-ac0630ea5496.PNG)
![img_2079](https://user-images.githubusercontent.com/30912049/40269853-34d21c2c-5bb6-11e8-97e6-58d3b45aa4ae.PNG)
![screen shot 2018-05-19 at 10 33 38 pm](https://user-images.githubusercontent.com/30912049/40269854-35094210-5bb6-11e8-9564-c6df03317237.png)
![screen shot 2018-05-19 at 10 33 55 pm](https://user-images.githubusercontent.com/30912049/40269855-35431f08-5bb6-11e8-867e-0a65f4645058.png)
![screen shot 2018-05-19 at 10 38 34 pm](https://user-images.githubusercontent.com/30912049/40269856-3574fd84-5bb6-11e8-8f33-95c7b0232134.png)
![screen shot 2018-05-19 at 10 38 52 pm](https://user-images.githubusercontent.com/30912049/40269857-35b3b1aa-5bb6-11e8-88fd-167bced2cdc7.png)

**Comment by dsanghan** [comment]
Fixed in 431
