### ISSUE TITLE
Forwarded emails from the sender's inbox shows name of the person the email was forwarded to, in the sender's inbox. 

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#16]
IOS version : 11.4.1
App version : 2.07

Steps to reproduce the issue:

1) Send a forwarded email to someone.
2) Open inbox.
3) Instead of the name of the actual sender that had sent you the mail, it will show the name of the person that email was forwarded to.

Screenshots:
1) The email is originally sent from Ziggo to the sender.   

![img_0415](https://user-images.githubusercontent.com/41723665/43442843-d833dae2-94bc-11e8-8dfc-de4e7d746651.png)

2) The sender forwards this email to Deborah, but when the sender opens his inbox, instead of ziggo ,it shows the name of the person it was forwarded to (i.e. Deborah)

![img_0413](https://user-images.githubusercontent.com/41723665/43442957-32de08fa-94bd-11e8-9d5a-eb3fbfff04dc.png)

Open ticket: 
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/17729727511

**Comment by dsanghan** [comment]
Fixed in update
