### ISSUE TITLE
Zoom feature truncates the details

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#18]
Device: Mac

Steps to reproduce the issue:
1) Open a mail from inbox
2) Try to Zoom in. It will cut some of the texts and it is required to adjust the view of the email.

Screenshot: 
<img width="581" alt="lxaga" src="https://user-images.githubusercontent.com/41723665/44092657-c1488034-9fee-11e8-8164-447e97c4713e.png">

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/17944186663

**Comment by Manan26895** [comment]
Please refer to this plain text email. 
![screen shot 2018-08-17 at 1 25 50 pm](https://user-images.githubusercontent.com/41723665/44254676-2731dd80-a221-11e8-9e49-7a6eed5254a8.png)

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O
