### ISSUE TITLE
Moving or deleting a message may fail

### ISSUE THREAD

**Issue by laizalimp0201** [CanaryMail/Tickets#2]
**Version of app: 397
Category: MacOS**

See videos. Issue appears to occur randomly, with no identifiably relevant activity required to trigger the issue. Issue occurs with newly created Gmail account without 2FA and with my personal account with 2FA. Tested by moving messages between the Inbox and a custom label/folder and between a custom label and the Trash. While testing, I noticed that the newly created Gmail label took a couple of minutes to appear in Canary, despite manually refreshing. Seems like a timing issue somewhere.

![image](https://user-images.githubusercontent.com/37428045/37501390-361d4550-2909-11e8-8786-802b4f3c8b11.png)
![image](https://user-images.githubusercontent.com/37428045/37501398-3c2880ae-2909-11e8-8abc-60f304f35aaa.png)

**Version of app: 2.0
iOS version: 11.2.6
Category: MacOS**

Repro Steps. 
Case 1. 
1. Delete an email 
2. Close App
3. Restart
** Deleted email reappears in Inbox
https://drive.google.com/open?id=1ixWr-cZUkPSAaWTX89zT9T1xG9xNaQPG

Case 2.
1. Delete an email 
2. Fetch 
** Delete successful 
https://drive.google.com/open?id=13STG5M3IqPvYDaXNbNQH_81OTxMPC96W

**Comment by CanaryMail** [comment]
Resolved in v413.
