### ISSUE TITLE
Text emails received from Canary appears small when viewed on other email providers.

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#24]
Device: IOS 

Screenshots: 
![image](https://user-images.githubusercontent.com/41723665/44297805-6cbfda80-a2f5-11e8-80c7-bfa16112b369.png)

![image](https://user-images.githubusercontent.com/41723665/44297808-7ba68d00-a2f5-11e8-9f14-962a8948727d.png)

Open ticket:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/17926602911

**Comment by dsanghan** [comment]
Fixed in update
