### ISSUE TITLE
Minor UI glitches on iPhone X

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#25]
Screenshots:

![image](https://user-images.githubusercontent.com/41723665/44463605-eaf1e900-a635-11e8-9554-003ab9133c3c.png)

![image](https://user-images.githubusercontent.com/41723665/44463625-f7764180-a635-11e8-8cac-9881f9e91aca.png)

**Comment by dsanghan** [comment]
Fixed in update
