### ISSUE TITLE
UI glitches, formatting and rendering issues on IOS 

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#27]
Screenshots: 
 
![](https://downloads.intercomcdn.com/i/o/73517499/c05bfd391471c091d85722d0/IMG_5710.PNG)

![](https://downloads.intercomcdn.com/i/o/73517500/d3b720596b2fff44c75ba026/IMG_5709.PNG)

![](https://downloads.intercomcdn.com/i/o/73517502/1d43e191520efb19f90f6c46/IMG_5708.PNG)

Open tickets: https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/mentions/conversations/17965448802

**Comment by dsanghan** [comment]
Fixed in update
