### ISSUE TITLE
Undo Send not visible 

### ISSUE THREAD

**Issue by laizalimp0201** [CanaryMail/Tickets#3]
Version of app: 2.0

iOS version: 11.2.6

Category: iOS

Description: Undo Send is not visible even if it's enabled. 
Please see screenshot. 
![image 2018-03-16 11-14-22](https://user-images.githubusercontent.com/37428045/37501888-39dc251a-290b-11e8-8388-4f6b3ed5217d.png)

**Comment by johnlreed** [comment]
For me, Undo appears after Sending disappears and when Archive appears in the bar.
