### ISSUE TITLE
Inline images fail to render if remote images are disabled" (IOS and Mac)

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#33]
Screenshot: 
![image](https://user-images.githubusercontent.com/41723665/46067020-6e51ad80-c193-11e8-887f-be5d0c13af2d.png)

Open ticket: https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/mentions/conversations/17913318082

**Comment by Manan26895** [comment]
Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/19228940708

**Comment by Manan26895** [comment]
Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/19131540807

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O
