### ISSUE TITLE
Editing shortcut for archive and delete doesn't work

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#37]
Issue: When the user presses Backspace on any message, it gets deleted instead of archived with the customised shortcut.

![image](https://user-images.githubusercontent.com/41723665/46598621-5cacc600-cb02-11e8-9d84-136393f7fb8c.png)

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/18895785187

**Comment by dsanghan** [comment]
Fixed in update
