### ISSUE TITLE
When dynamic fonts enabled, text will cut off

### ISSUE THREAD

**Issue by Luci09** [CanaryMail/Tickets#4]
Version of app: 2.01
iOS version: 11.2.6

Steps to repro: 
1. Enable "Use Dynamic Fonts" inside Canary for iOS
2. Go to iOS Settings -->Display & Brightness --> Text size --> make the text bigger 
3. Go to Canary App --> List of accounts --> text will be cut 

Was able to repro on my end.

Screenshot to issue: 
![textcut](https://user-images.githubusercontent.com/23071857/37554881-b4c35730-29e7-11e8-8cbd-be15b366dc8d.jpg)

Link to issue : 
https://app.intercom.com/a/apps/d1498q0a/inbox/inbox/1861960/conversations/15206724925

**Comment by johnlreed** [comment]
Issue confirmed.

**Comment by dsanghan** [comment]
Fixed in update
