### ISSUE TITLE
In IMAP account, new folder creates subdirectories and a new "INBOX"

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#41]
Device: IOS
 
Screen recording: 
https://drive.google.com/open?id=1C0L-uJPQGnd5C5OhTDtjHydrqPjZ0uQC

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/18993376349

**Comment by dsanghan** [comment]
@Manan26895 Please test on other email providers. If you see the issue then re-open. Otherwise ask for a test account.
