### ISSUE TITLE
While forwarding a message, the sender's email address is not accessible but while replying it is.

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#43]
Open tickets: https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/search/conversations/19050653064?q=pepperfry
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/search/conversations/19075120181?q=issue%20with%20the%20app

**Comment by dsanghan** [comment]
Fixed in update
