### ISSUE TITLE
Reply to threaded messages are only reflected in the inbox by a badge count, the actual message can't be found under inbox.

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#44]
Steps: 
1) If there is a reply to a thread, the inbox shows that there is a message (in terms of only a badge count) but the actual message is not visible under the inbox.
2) The user has to look for the folder in which this message is received instead of just finding the whole conversation in the inbox.

screen recording: is attached inside the ticket, somehow can't attach here.

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/19182734656

**Comment by dsanghan** [comment]
Fixed in update
