### ISSUE TITLE
In IMAP account, the emails can't be moved from search to any other folders

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#45]
Screen recording: https://downloads.intercomcdn.com/i/o/83410594/76ea643ea61e342cf678959b/Screen+Recording+2018-08-28+at+10.07.47.mov

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/19305210117

**Comment by dsanghan** [comment]
Fixed in update
