### ISSUE TITLE
Transfer issue of emails from one email account to a folder of another email account

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#46]
Device: iPhone 7 (IOS 12.0.1)
Canary Version: 2.13
Steps: 
1. Select an email from an account.
2. Transfer it to any folder (custom or local) of other account.
3. It will disappear from the inbox but will not be transferred. 

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/18982327242

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O
