### ISSUE TITLE
Mark as spam failure on swipe for yahoo emails on IOS

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#49]
Steps to repro:
1) Open Yahoo's inbox.
2) Try to mark an email as spam using swipe action.
3) The email will disappear for a second, but will be reappear almost instantly thereafter.

Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/19939918026

**Comment by dsanghan** [comment]
Fixed in update
