### ISSUE TITLE
Unable to attach multiple pictures when composing new email

### ISSUE THREAD

**Issue by Luci09** [CanaryMail/Tickets#5]
Version of the app: 2.02
iOS version: 11.2.6

Steps to repro: 

1. Hit the compose new email icon
2. Tap on the attachment paper clip 
3. Use the Photos option
4. Select multiple pictures (3-4 pictures) 

Was able to repro from my end, on my iPhone 7 device. 

Recording with the bug: 

https://www.dropbox.com/s/mne5tskx6lqszvm/attachment%20bug.mp4?dl=0

Link to issue: 

https://app.intercom.com/a/apps/d1498q0a/inbox/inbox/1861960/conversations/15329160237

**Comment by Luci09** [comment]
https://app.intercom.com/a/apps/d1498q0a/inbox/inbox/1861960/conversations/15240386343

**Comment by johnlreed** [comment]
This isn't only with multiple images. Attaching a single image fails for me.

**Comment by dsanghan** [comment]
Fixed as of 417
