### ISSUE TITLE
Assigning the following keys to delete and archive will only delete the message in every case.

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#51]
Screenshot:

![screen shot 2018-12-20 at 7 34 43 pm](https://user-images.githubusercontent.com/41723665/50288986-8896e100-048d-11e9-99d1-d50e6adf4b4a.png)

Open tickets: 
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/19996948766

**Comment by dsanghan** [comment]
Fixed in update
