### ISSUE TITLE
Dropbox icon doesn't respond and re direct to login screen on Mac

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#54]
Open tickets:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/search/conversations/20242901857?q=dropbox

https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/search/conversations/20302783591?q=dropbox

**Comment by dsanghan** [comment]
Fixed in update
