### ISSUE TITLE
Snoozed emails fail to return to inbox at the desired (set) time on IOS.

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#55]
Steps to repro:
1) Snooze an email using "Pick a date".
2) Set the time you want the email to wake.
3) The email fails to return to the inbox at the desired time and stays in the snoozed folder even after the time is lapsed.

**Note:** It would only return to the inbox if you open the snooze folder (if at all it returns) . If it doesn't, the only way out is to restart the app. The snooze folder will then be empty as expected. 

Open tickets: https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/20254456549

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O.
