### ISSUE TITLE
Signatures fail to retain colours on Mac.

### ISSUE THREAD

**Issue by Manan26895** [CanaryMail/Tickets#56]
**Note:** The signature tends to appear as plain text (black) with no or limited colours only when viewed in Canary on Mac. On other email apps, the colours are visible. Also, the IOS version of Canary has no issues. It displays the colours correctly. Please refer the screenshots below. 

1)![screen shot 2019-01-22 at 2 02 19 pm](https://user-images.githubusercontent.com/41723665/51521717-6f4ad100-1e4d-11e9-931c-710a72e4eff0.png)

2)![screen shot 2019-01-22 at 2 02 09 pm](https://user-images.githubusercontent.com/41723665/51521737-7f62b080-1e4d-11e9-9dc1-4af2e0445a7e.png)

3)  From IOS: 
![screen shot 2019-01-22 at 2 08 03 pm](https://user-images.githubusercontent.com/41723665/51521937-07e15100-1e4e-11e9-916a-fe31486ca29a.png)

**Comment by Manan26895** [comment]
Open tickets: https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/2246302/conversations/20458827936

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O.
