### ISSUE TITLE
Canary 411/macOS: Cleaner action buttons unresponsive

### ISSUE THREAD

**Issue by johnlreed** [CanaryMail/Tickets#6]
Upon using the Cleaner feature to bulk-select messages, the follow-up Archive, Delete, Snooze, and other buttons are unresponsive and have no effect on selected messages. See attached video.

![2018-04-05 13 59 54](https://user-images.githubusercontent.com/4260517/38383174-c5562cb6-38d9-11e8-8dd7-92ff8cdc3738.gif)

**Comment by CanaryMail** [comment]
Resolved in v413.
