### ISSUE TITLE
Cannot Use Snooze after Searching

### ISSUE THREAD

**Issue by adrianabranzei** [CanaryMail/Tickets#67]
Hi!
Replicating steps:
1. Go on the Mac version
2. Search for an email. I searched "Sephora"for example.
3. I find my email, click it and if I want to snooze it, the button appears to be grayed out and I can't do it.
Image: 
<img width="675" alt="Screen Shot 2019-06-19 at 14 23 43" src="https://user-images.githubusercontent.com/51986220/59761800-69430a00-929e-11e9-8f48-bbffa050ce77.png">

Here is the support ticket as well: https://canarymail.zendesk.com/agent/tickets/794

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O.
