### ISSUE TITLE
Typo discovered by a customer on an error message

### ISSUE THREAD

**Issue by adrianabranzei** [CanaryMail/Tickets#73]
Hi!
On the Mac app.
On this error message "Encryption Unavailable: Some **receipients** have not set up encryption," please correct the misspelling of the word, recipients. Thank you!

Ticket: https://canarymail.zendesk.com/agent/tickets/1019

**Comment by adrianabranzei** [comment]
<img width="901" alt="Screen Shot 2019-07-21 at 12 30 19" src="https://user-images.githubusercontent.com/51986220/61589499-554b3a80-abb3-11e9-9835-b80261d97c94.png">

**Comment by sarahscott12** [comment]
Verified. This issue is fixed in V 3.O
