### ISSUE TITLE
[MacOS] Archive multiple messages failure

### ISSUE THREAD

**Issue by applesolbrilla** [CanaryMail/Tickets#8]
MacOS
App version 411

Steps to reproduce the issue:

1. Select multiple messages.
2. Click "Archive Threads".

Screen recording: https://www.dropbox.com/s/cq7jkljfn0xmn15/Archive%20Multiple%20Messages%20Failure.mov?dl=0

Tag: Archive Multiple Messages

Open ticket:
https://app.intercom.io/a/apps/d1498q0a/inbox/inbox/1902146/conversations/15527226961

**Comment by CanaryMail** [comment]
Resolved in v413.
